/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author EQUIPO
 */
public class frm_Laberinto extends javax.swing.JFrame {

    /**
     * Creates new form frm_Laberinto
     */
    public frm_Laberinto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lab21 = new javax.swing.JLabel();
        lab31 = new javax.swing.JLabel();
        lab41 = new javax.swing.JLabel();
        lab42 = new javax.swing.JLabel();
        lab32 = new javax.swing.JLabel();
        lab22 = new javax.swing.JLabel();
        lab12 = new javax.swing.JLabel();
        lab03 = new javax.swing.JLabel();
        lab13 = new javax.swing.JLabel();
        lab23 = new javax.swing.JLabel();
        lab33 = new javax.swing.JLabel();
        lab52 = new javax.swing.JLabel();
        lab43 = new javax.swing.JLabel();
        lab53 = new javax.swing.JLabel();
        lab44 = new javax.swing.JLabel();
        lab54 = new javax.swing.JLabel();
        lab34 = new javax.swing.JLabel();
        lab55 = new javax.swing.JLabel();
        lab24 = new javax.swing.JLabel();
        lab45 = new javax.swing.JLabel();
        lab04 = new javax.swing.JLabel();
        lab35 = new javax.swing.JLabel();
        lab05 = new javax.swing.JLabel();
        lab14 = new javax.swing.JLabel();
        lab15 = new javax.swing.JLabel();
        lab25 = new javax.swing.JLabel();
        lab01 = new javax.swing.JLabel();
        lab00 = new javax.swing.JLabel();
        lab10 = new javax.swing.JLabel();
        lab20 = new javax.swing.JLabel();
        lab30 = new javax.swing.JLabel();
        lab40 = new javax.swing.JLabel();
        lab50 = new javax.swing.JLabel();
        lab51 = new javax.swing.JLabel();
        lab02 = new javax.swing.JLabel();
        lab11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab21.setText("jLabel1");

        lab31.setText("jLabel1");

        lab41.setText("jLabel1");

        lab42.setText("jLabel1");

        lab32.setText("jLabel1");

        lab22.setText("jLabel1");

        lab12.setText("jLabel1");

        lab03.setText("jLabel1");

        lab13.setText("jLabel1");

        lab23.setText("jLabel1");

        lab33.setText("jLabel1");

        lab52.setText("jLabel1");

        lab43.setText("jLabel1");

        lab53.setText("jLabel1");

        lab44.setText("jLabel1");

        lab54.setText("jLabel1");

        lab34.setText("jLabel1");

        lab55.setText("jLabel1");

        lab24.setText("jLabel1");

        lab45.setText("jLabel1");

        lab04.setText("jLabel1");

        lab35.setText("jLabel1");

        lab05.setText("jLabel1");

        lab14.setText("jLabel1");

        lab15.setText("jLabel1");

        lab25.setText("jLabel1");

        lab01.setText("jLabel1");

        lab00.setText("jLabel1");

        lab10.setText("jLabel1");

        lab20.setText("jLabel1");

        lab30.setText("jLabel1");

        lab40.setText("jLabel1");

        lab50.setText("jLabel1");

        lab51.setText("jLabel1");

        lab02.setText("jLabel1");

        lab11.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lab50)
                        .addGap(18, 18, 18)
                        .addComponent(lab51)
                        .addGap(18, 18, 18)
                        .addComponent(lab52)
                        .addGap(18, 18, 18)
                        .addComponent(lab53)
                        .addGap(18, 18, 18)
                        .addComponent(lab54)
                        .addGap(18, 18, 18)
                        .addComponent(lab55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab00)
                                .addGap(18, 18, 18)
                                .addComponent(lab01)
                                .addGap(18, 18, 18)
                                .addComponent(lab02)
                                .addGap(18, 18, 18)
                                .addComponent(lab03)
                                .addGap(18, 18, 18)
                                .addComponent(lab04))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab10)
                                .addGap(18, 18, 18)
                                .addComponent(lab11)
                                .addGap(18, 18, 18)
                                .addComponent(lab12)
                                .addGap(18, 18, 18)
                                .addComponent(lab13)
                                .addGap(18, 18, 18)
                                .addComponent(lab14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab20)
                                .addGap(18, 18, 18)
                                .addComponent(lab21)
                                .addGap(18, 18, 18)
                                .addComponent(lab22)
                                .addGap(18, 18, 18)
                                .addComponent(lab23)
                                .addGap(18, 18, 18)
                                .addComponent(lab24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab30)
                                .addGap(18, 18, 18)
                                .addComponent(lab31)
                                .addGap(18, 18, 18)
                                .addComponent(lab32)
                                .addGap(18, 18, 18)
                                .addComponent(lab33)
                                .addGap(18, 18, 18)
                                .addComponent(lab34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lab40)
                                .addGap(18, 18, 18)
                                .addComponent(lab41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lab42)
                                .addGap(18, 18, 18)
                                .addComponent(lab43)
                                .addGap(18, 18, 18)
                                .addComponent(lab44)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab45)
                            .addComponent(lab15)
                            .addComponent(lab05)
                            .addComponent(lab25)
                            .addComponent(lab35))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab00)
                    .addComponent(lab01)
                    .addComponent(lab02)
                    .addComponent(lab03)
                    .addComponent(lab04)
                    .addComponent(lab05))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab15)
                    .addComponent(lab14)
                    .addComponent(lab13)
                    .addComponent(lab12)
                    .addComponent(lab11)
                    .addComponent(lab10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab25)
                    .addComponent(lab24)
                    .addComponent(lab23)
                    .addComponent(lab22)
                    .addComponent(lab21)
                    .addComponent(lab20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab35)
                    .addComponent(lab34)
                    .addComponent(lab33)
                    .addComponent(lab32)
                    .addComponent(lab31)
                    .addComponent(lab30))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab45)
                    .addComponent(lab44)
                    .addComponent(lab40)
                    .addComponent(lab41)
                    .addComponent(lab43)
                    .addComponent(lab42))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab50)
                    .addComponent(lab51)
                    .addComponent(lab52)
                    .addComponent(lab53)
                    .addComponent(lab54)
                    .addComponent(lab55))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Laberinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lab00;
    public static javax.swing.JLabel lab01;
    public static javax.swing.JLabel lab02;
    public static javax.swing.JLabel lab03;
    public static javax.swing.JLabel lab04;
    public static javax.swing.JLabel lab05;
    public static javax.swing.JLabel lab10;
    public static javax.swing.JLabel lab11;
    public static javax.swing.JLabel lab12;
    public static javax.swing.JLabel lab13;
    public static javax.swing.JLabel lab14;
    public static javax.swing.JLabel lab15;
    public static javax.swing.JLabel lab20;
    public static javax.swing.JLabel lab21;
    public static javax.swing.JLabel lab22;
    public static javax.swing.JLabel lab23;
    public static javax.swing.JLabel lab24;
    public static javax.swing.JLabel lab25;
    public static javax.swing.JLabel lab30;
    public static javax.swing.JLabel lab31;
    public static javax.swing.JLabel lab32;
    public static javax.swing.JLabel lab33;
    public static javax.swing.JLabel lab34;
    public static javax.swing.JLabel lab35;
    public static javax.swing.JLabel lab40;
    public static javax.swing.JLabel lab41;
    public static javax.swing.JLabel lab42;
    public static javax.swing.JLabel lab43;
    public static javax.swing.JLabel lab44;
    public static javax.swing.JLabel lab45;
    public static javax.swing.JLabel lab50;
    public static javax.swing.JLabel lab51;
    public static javax.swing.JLabel lab52;
    public static javax.swing.JLabel lab53;
    public static javax.swing.JLabel lab54;
    public static javax.swing.JLabel lab55;
    // End of variables declaration//GEN-END:variables
}
